#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LATEX_HEADER: \usepackage{geometry}\geometry{a4paper,left=15mm,right=20mm,top=20mm,bottom=30mm}

\(\mathbb{DISCLAMER}\), this stuff should be taken as a quick indication, if you think something's wrong, go look in the course.
Also, if you spot any mistakes please tell me

* misc
 - smol means \(n < 30 \), big means \(n \ge 30\);
 - \( \displaystyle (S^*)^2 = \frac{n}{n-1} S^2 = \frac{1}{n-1} \sum_{i=1}^{n} (X_i- \bar{X})^2\);
 - \( S^* = \sqrt{(S^*)^2}, S = \sqrt{S^2} \), duh;
 - \(D^2(X) = \mathbb{E}(X^2) - \left(\mathbb{E}(X)\right)^2\);
 - Maximum likelihood estimator = (Metoda) verosimilității maxime
 - the \( \chi^2 \)-test is gud for testing the expected frequency vs the frequency you got
  (like on a coin/ on dice);
 - \(cov(X, Y) = \mathbb{E}\left(( X - \bar{X}  ) (Y - \bar{Y}) \right) = \mathbb{E}(XY) - \mathbb{E}(X)\mathbb{E}(Y)\);
 - when testing try to reject the null hypotesis (ie. chose he other thing as the null hypotesis: if ya want to check if
   \(r > 0.8\) make \( (H_0): r = 0.8 \) and \( (H_1): r > 0.8 \) )
 (also look at [[https://en.wikipedia.org/wiki/Exclusion_of_the_null_hypothesis]]);
 - P-value: 
   - \(P_v \leq \alpha \implies (H_0) \) fals,
   - \(P_v = \) = "Probabilitatea de a obtine un rezultat cel putin la fel de extrem ca cel observat,
   - \(P_v = \mathbb{P}(T\geq t|H) \) for a one-sided (right tail) test,
   - \(P_v = \mathbb{P} (T\leq t|H) \) for a one-sided (left tail) test,
   - \(P_v = 2 \min \left\{ \mathbb{P} ( T \leq t | H ) , \mathbb{P} ( T \geq t | H ) \right\} \) for a two-sided test
   - more stuff at C6/pg 3;

* Confidence intervals - tl;dr
** for the average
#+begin_export latex
\renewcommand{\arraystretch}{2}
  \begin{tabular}{|l|l|l|l|l|l|}
  \hline
  type &  where to find & \(X\) type & $n$ size & \(\sigma\) known & the interval  \\
\hline
  bilateral & C5 - pg 2   & \(~\mathcal{N} (\mu, \sigma^2) \) & whatever & yes &
  \( \mu \in \left(\bar{X} - \dfrac{\sigma}{\sqrt{n}} z_{1-\alpha/2}, \bar{X} + \dfrac{\sigma}{\sqrt{n}} z_{1-\alpha/2}\right)
 \) \\ \hline
bilateral & C5 - pg 3   & whatever & big & yes &
  \( \mu \in \left(\bar{X} - \dfrac{\sigma}{\sqrt{n}} z_{1-\alpha/2}, \bar{X} + \dfrac{\sigma}{\sqrt{n}} z_{1-\alpha/2}\right)
 \) \\ \hline
 no sup & C5 - pg 3   & \(\sim\mathcal{N} (\mu, \sigma^2) \) & big & yes &
  \( \mu \in \left(\bar{X} - \dfrac{\sigma}{\sqrt{n}} z_{1-\alpha}, \infty \right)
 \) \\ \hline
 no inf & C5 - pg 3   & \(\sim\mathcal{N} (\mu, \sigma^2) \) & big & yes &
  \( \mu \in \left(-\infty, \bar{X} + \dfrac{\sigma}{\sqrt{n}} z_{1-\alpha}\right)
 \) \\ \hline
 bilateral & C5 - pg 3 bot   & whatever & big & no &
  \( \mu \in \left(\bar{X} - \dfrac{S^*}{\sqrt{n}} z_{1-\alpha/2}, \bar{X} + \dfrac{S^*}{\sqrt{n}} z_{1-\alpha/2}\right)
 \) \\ \hline
unilateral & C5 - pg 4    & whatever & big & no &
like rows 2 and 3 but with \(S^*\)
  \\ \hline
bilateral & C5 - pg 5   & \(\sim\mathcal{N} (\mu, \sigma^2) \)  & smol & no &
  \( \mu \in \left(\bar{X} - \dfrac{S^*}{\sqrt{n}} t_{1-\alpha/2,n-1}, \bar{X} + \dfrac{S^*}{\sqrt{n}} t_{1-\alpha/2, n-1}\right)
 \) \\ \hline
unilateral & C5 - pg 5    & \(\sim\mathcal{N} (\mu, \sigma^2) \)  & smol & no &
like rows 2 and 3 but with \(S^*\) and \(t_{1-\alpha, n-1} 
 \) \\ \hline

  \end{tabular}

#+end_export

** for the variance (dispersion)
#+begin_export latex
\renewcommand{\arraystretch}{2}
  \begin{tabular}{|l|l|l|l|l|l|}
  \hline
  type &  where to find & \(X\) type & $n$ size & \(\mu\) known & the interval  \\
\hline
  bilateral & C5 - pg 6   & \(\sim\mathcal{N} (\mu, \sigma^2) \) & smol & yes &
  \( \displaystyle \sigma^2 \in \left( \frac{\sum_{i=1}^n (X_i-\mu)^2}{\chi^2_{\alpha/2, n}}, 
\frac{\sum_{i=1}^n (X_i-\mu)^2}{\chi^2_{1-\alpha/2, n}}  \right)
\) \\ \hline

bilateral & C5 - pg 6   & \(\sim\mathcal{N} (\mu, \sigma^2) \) & smol & no &
  \( \displaystyle \sigma^2 \in \left( \frac{(n-1) (S^*)^2 }{\chi^2_{\alpha/2, n-1}}, 
\frac{(n-1) (S^*)^2 }{\chi^2_{1-\alpha/2, n-1}}, \right)
 \) \\ \hline

  \end{tabular}
#+end_export

\medskip
for \(n\) large, look at C5 pg 7 - obs 1.3
tl;dr we make it a normal distribution

** for two selections 
look at C5 pg 8-10

* "Testarea ipotezelor statistice"\footnote{yea, ik, not the proper quotes} - tl;dr
** For the average
\((H_0): \mu = \mu_0\)
\medskip

#+begin_export latex
  \renewcommand{\arraystretch}{2}
  \begin{tabular}{|l|l|l|l|l|l|l|}
  \hline
  name   &    where to find & \(X\) type & $n$ size & \(\sigma\) known & $\text{thing}_0$ & bilateral tl;dr  \\
\hline
  \(Z\) test  & C6 - pg 6-9   & \(\sim\mathcal{N} (\mu, \sigma^2) \) & big & yes &
  \(z_0 = \dfrac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} \) & \(z_0 \in \left( -z_{1-\alpha/2}, z_{1-\alpha/2} \right) \) \\
 \hline
  \(T\) test  & C6 - pg 10-13   & \(\sim\mathcal{N} (\mu, \sigma^2) \) & smol & no  &
  \(z_0 = \dfrac{\bar{x} - \mu_0}{s^* / \sqrt{n}} \) & \( t_0 \in \left( -t_{1-\alpha/2,n-1}, t_{1-\alpha/2, n-1} \right) \) \\
\hline
  \end{tabular}

#+end_export

** For the variance (dispersion)
\((H_0): \sigma = \sigma_0\)
\medskip

  \(\chi^2\)-test

At C6 - pg 13-14
\medskip

#+begin_export latex
\(\chi^2_0 = \dfrac{(n-1) (s^*)^2}{\sigma_0^2} \)
\medskip

\(H_0\) is acepted (or pedantically  "not rejected") if:

\( \chi^2_0 \in (\chi^2_{1-\alpha/2, n-1}, \chi^2_{1-\alpha/2, n-1}) \)
#+end_export

\medskip
also see S10/S11 - pg 4

*** \(F\) test for dispertion ratios
see C6 p14 - 16
also see S10/S11 - pg9


* "Teoria concordanței" - tl;dr
 the rank thing is (sometimes) calculated as the mean of the indices the value is equal - just look at 2b

 - ex 1: Spearman & pearson coefficient
 - ex 2: Pearson coefficient with an outlier
 - ex 3: \(\rho_{X, Y} = 0 \) with \(\alpha = 0.05\)
  - is \( y= x^3-1\) in contradiction with the other stuff
  - the usual stuff
 - ex 4: Spearman coefficent with some frequencies
 - the other ones are about the same thing mostly

\bigskip

Sun Tzu said: “The opportunity to secure ourselves against restanță lies in our own hands, 
but the opportunity of passing the exam is provided by the professor himself.”
# Be extremely subtle even to the point of formlessness. 
# Be extremely mysterious even to the point of soundlessness.
# Thereby you can be the director of the exam's fate”.
